### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by musm**
Basically all of these packages have been deprecated.

### CODE REVIEW

**Comment by musm** [comment]
@SimonDanisch do you want to archive https://github.com/JuliaGL/GLWindow.jl  https://github.com/JuliaGL/GLVisualize.jl ? 
I was going through these repos trying to catch up to speed on latest Makie changes. Hopefully this better reflects the latest changes.

**Comment by SimonDanisch** [comment]
Yeah, sounds like a plan! @louisponet wanted to keep some of those alive, but I guess mostly GLAbstraction?

**Comment by musm** [comment]
The repo says `GLAbstraction` is archived by its owner https://github.com/JuliaGL/GLAbstraction.jl. Is that not true then?

**Comment by louisponet** [comment]
Yea Simon archived it, although in my opinion there's no real need to since it works with v1.6 and I think it's a valid abstraction layer over pure OpenGL. GLVisualize I don't think works or is used anywhere at all anymore.

**Comment by musm** [comment]
@louisponet  thank you for the reply. I went ahead and unarchived GLAbstraction and archived GLVisualize and GLWindow.

**Pull request merged**
