### PR TITLE
Remove need build.jl & deps.jl

### PR DESCRIPTION
**Pull request by IanButterworth**
Just a suggestion, as there may have been some logic to the way it was set up that I was missing, but this seems to provide the same functionality (?)

### CODE REVIEW

**Comment by musm** [comment]
LGTM

**Comment by IanButterworth** [comment]
I have completely forgotten about this PR, but from a quick review it seems the ENV check should go in `__init__` right?

**Comment by musm** [comment]
Updated in https://github.com/JuliaGL/ModernGL.jl/pull/64/files#diff-f792db789fac2dcd6d58e79c19224d5c5cf4832cdc7881e130b0d327476a2b48R93

**Comment by musm** [comment]
Good point, yeah we defintely need to get it and initialization time instead of precompiling the value 😅

**Pull request closed without merging**
