### PR TITLE
Use const Refs to store gl function pointers instead of mutable structs

### PR DESCRIPTION
**Pull request by thraen**

### CODE REVIEW

**Comment by musm** [comment]
This looks more reasonable. Was there a specific use case to make this change?

**Comment by thraen** [comment]
I think this came up when I profiled my code and saw more allocations than I expected

**Comment by SimonDanisch** [comment]
Well, that sounds like a pretty important change then :-D

**Comment by musm** [comment]
Sounds reasonable. In any case  ref make more sense for the code here. I'll merge sans objections.

**Pull request merged**
